# Generated by Django 4.1.2 on 2022-10-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceID',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
