# Generated by Django 4.1.2 on 2022-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
